Layout/LineLength:
  Max: 100

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false
